btb_csv_path: '/flush/iulta54/Research/P11-BTB_DEEP_LEARNING/dataset_csv_file/BTB_AGGREGATED_CLINICAL_AND_WSI_INFORMATION_KS_LK_GOT_UM_LUND_ANONYM_20240405.csv'

output_dir: '/flush/iulta54/Research/P11-BTB_DEEP_LEARNING/outputs' # folder where to save output
experiment_name: 'BTB_csv_for_training'
save_classification_task_yaml_template : True # saves a .yaml file that matches the clam/config/classification/task config files. Will not have the full paths to the .csv files dor the feature directory since these will change based on the computer the code is run on.

# for which framework (hipt, and/or clam)
framework : [clam, hipt]

# split configurations
test_fraction : 0.3
number_of_repetitions : 1
number_of_folds : 10
random_seed : 29122009
validation_fraction : 0.2 # only used if the number_of_folds == 1

# classification type and class split settings

# Specify at which level the classification should be performed. 
# tumor_category : using the TUMOR_CATEGORY column to get the class information
# tumor_family : using the WHO_TUMOR_FAMILY column to get the class information
# tumor_type : using the WHO_TUMOR_type column to get the class information

classification_level : tumor_family
class_column_name : WHO_TUMOR_FAMILY
classes_to_exclude : []
min_nbr_subjects_per_class : 10 # Set the minimum number of subjects per class. Set to -1 to not use this as filter

# site (centre) split settings TODO - make split take into account the site
site_column_name : SITE
site_to_exclude : []

# stratification settings
class_stratification : True
site_stratification : False

# set if to filter those files that do not have extracted features
check_available_features : True 
feature_dir : /flush/iulta54/Research/Data/BTB/EXTRACTED_FEATURES/clam_resnet50/BTB_CLAM_fp_feature_extraction/2024-04-03/pt_files # Path to where the extracted .pt feature files are saved. 
skip_missing_features : True # Set to True to raise an error when not all the slides_ids have extracted features. This is useful since will make sure that all the files are available for training, val and test.






