# task configuration for running MIL training within the CLAM framework

description : 'tumor_category' # Used to select the csv_file files describing the dataset and the splits
version : all

data_root_dir : ${local_directories.feature_directory}/clam_features_mag_x${magnification}_size_${patch_size}/${feature_extractor}
csv_path : ${local_directories.dataset_csv_files}/nonparametric_bootstrapping/${task.description}/${task.version}/dataset_descriptor.csv
split_dir : ${local_directories.dataset_csv_files}/nonparametric_bootstrapping/${task.description}/${task.version}/clam/repetition_0

# data_root_dir : /local/data2/iulta54/Data/BTB/histology_features/clam_vit_conch_mag_x20_size_224/BTB_CLAM_vit_conch_features_mag_x20_size_224/2024-04-18 # Path to where the features are located (this is the path to the experiment_name folder, not the actual feature folder)
# csv_path : /local/data1/iulta54/Code/BTB_DEEP_LEARNING/outputs/BTB_csv_for_training/dataset_summary/dataset_description_tumor_category_rep_0_folds_5.csv # Path to the dataset_descriptor csv file
# split_dir : /local/data1/iulta54/Code/BTB_DEEP_LEARNING/outputs/BTB_csv_for_training/clam/tumor_category_reps_1_folds_5/repetition_0 # Path to where the split .csv files for this task are located.

n_classes : 7 # Number of classes
subtyping : True # Set to True if this is a sub-typing problem (TODO - check the code for why this is needed).

label_dict : # specify the classes (class to integer)
  Choroid plexus tumors: 0
  Embryonal tumors: 1
  Germ cell tumors: 2
  Gliomas, glioneuronal tumors, and neuronal tumors: 3
  Meningiomas: 4
  Mesenchymal, non-meningothelial tumors: 5
  Tumors of the sellar region: 6

ignore : [] # TODO - check code to see what this does