# task configuration for running MIL training within the CLAM framework
description : 'Test dataset' # give a short description of the dataset (Not mandatory, just used for plotting).

data_root_dir : /run/media/iulta54/Expansion/Datasets/BTB/SCRIPTS/features/clam_vit_hipt/BTB_CLAM_fp_feature_extraction/2024-04-03 # Path to where the features are located (this is the path to the experiment_name folder, not the actual feature folder)
csv_path : /run/media/iulta54/Expansion/Datasets/BTB/SCRIPTS/pre_processing/outputs/BTB_csv_for_training/dataset_summary/repetition_0/dataset_description_repetition_0.csv # Path to the dataset_descriptor csv file
split_dir : /run/media/iulta54/Expansion/Datasets/BTB/SCRIPTS/pre_processing/outputs/BTB_csv_for_training/clam/repetition_0 # Path to where the split .csv files for this task are located.


n_classes : 7 # NUmber of classes
subtyping : True # Set to True if this is a sub-typing problem (TODO - check the code for why this is needed).

label_dict : # specify the classes (class to integer)
  CHOROID_PLEXUS_TUMORS : 0
  CNS_EMBRYONAL_TUMORS : 1
  GERM_CELL_TUMORS : 2
  GLIOMAS_GLIONEURAL_NEURONAL_TUMORS : 3
  MENINGIOMAS : 4
  PINEAL_REGION_TUMORS : 5 
  TUMORS_OF_THE_STELLAR_REGION : 6

ignore : [] # TODO - check code to see what this does