btb_csv_path: '/run/media/iulta54/Expansion/Datasets/BTB/SUMMARY_COUNTS_AND_PLOTS/overall_summary_data_with_wsi_paths_20240326.csv'

output_dir: '/run/media/iulta54/Expansion/Datasets/BTB/SCRIPTS/pre_processing/outputs' # folder where to save output
experiment_name: 'BTB_csv_for_training'

# for which framework (hipt, and/or clam)
framework : [clam]

# split configurations
test_fraction : 0.3
number_of_repetitions : 1
number_of_folds : 5
random_seed : 29122009
validation_fraction : 0.2 # only used if the number_of_folds == 1

# classification type and class split settings

# Specify at which level the classification should be performed. 
# tumor_category : using the TUMOR_CATEGORY column to get the class information
# tumor_family : using the WHO_TUMOR_FAMILY column to get the class information
# tumor_type : using the WHO_TUMOR_type column to get the class information

classification_level : tumor_category
class_column_name : WHO_TUMOR_CATEGORY
classes_to_exclude : ['EYE TUMORS', 'MESENCHYMAL_NON_MENINGOTHELIAL_TUMORS', 'NEUROENDOCRINE_NEOPLASM', 'SOFT_TISSUE_TUMORS']
min_nbr_subjects_per_class : 10 # Set the minimum number of subjects per class. Set to -1 to not use this as filter

# site (centre) split settings
site_column_name : SITE
site_to_exclude : []

# stratification settings
class_stratification : True
site_stratification : True

# set if to filter those files that do not have extracted features
check_available_features : False 
feature_dir : /run/media/iulta54/Expansion/Datasets/BTB/SCRIPTS/features/clam_vit_hipt/BTB_CLAM_fp_feature_extraction/2024-04-03/pt_files # Path to where the extracted .pt feature files are saved. 
skip_missing_features : True # Set to True to raise an error when not all the slides_ids have extracted features. This is useful since will make sure that all the files are available for training, val and test.






